name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Java
      run: sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
    - name: Install Maven
      run: sudo apt-get install -y maven
    - name: Run tests
      run: mvn test
